export const MAIN_SET_MESSAGE = 'MAIN_SET_MESSAGE'
export const MAIN_SET_FETCHING = 'MAIN_SET_FETCHING'

export const NAVIGATION_SET_TITLE = 'NAVIGATION_SET_TITLE'
export const NAVIGATION_SET_DISPLAY = 'NAVIGATION_SET_DISPLAY'

export const PROJECTS_SET_DATA = 'PROJECTS_SET_DATA'
export const PROJECTS_SET_DISPLAY = 'PROJECTS_SET_DISPLAY'

export const PROJECT_SET_CURRENT = 'PROJECT_SET_CURRENT'
export const WORKSPACE_SET_CURRENT = 'WORKSPACE_SET_CURRENT'

export const PROJECT_SET_LIST = 'PROJECT_SET_LIST'
export const WORKSPACE_SET_LIST = 'WORKSPACE_SET_LIST'
